
send_now:
  name: Send current position now
  description: Reads the current latitude/longitude from the selected device_tracker and posts to the configured server immediately.
  fields:
    entity_id:
      name: Entity ID
      description: (Optional) device_tracker entity to send. If omitted, the first configured device is used.
      example: device_tracker.bananastefan
      required: false
      selector:
        entity:
          domain: device_tracker

test_post:
  name: Send test point (diagnostic)
  description: Sends a test coordinate to the server using the configured device (default index 0) to verify connectivity.
  fields:
    device_index:
      name: Device index
      description: Optional zero-based device index as listed in the integration options.
      required: false
      example: 0
    lat:
      name: Latitude
      description: Optional latitude override (defaults to 48.137154).
      required: false
      example: 48.137154
    lon:
      name: Longitude
      description: Optional longitude override (defaults to 11.576124).
      required: false
      example: 11.576124

update_device:
  name: Update configured device
  description: Update a device in the PenguinGEOMap options by its index (as shown in the options list).
  fields:
    index:
      name: Device index
      description: Zero-based device index (0 for the first device).
      required: true
      example: 0
    name:
      name: Name
      required: false
    entity_id:
      name: Entity ID
      required: false
    server_url:
      name: Server URL
      description: Base server URL (without /api/ingest.php).
      required: false
      example: https://garmin.penguinparade.eu/penguin_geomap_server
    key:
      name: Key
      required: false
    enabled:
      name: Enabled
      required: false
    verify_ssl:
      name: Verify SSL
      required: false
    poll_seconds:
      name: Poll seconds
      description: Poll interval per device (0 to disable).
      required: false
